### ISSUE TITLE
Add support for #[relectapi(flatten)]

### ISSUE THREAD

**Issue by elilabes** [thepartly/reflectapi#19]
The schemars package for open api supports flattening properties on the wire and in the generate code like so:

```
#[schemars(flatten)]
pub some_property: SomeType
```

We need reflectapi to support this to, so that the generated code matches what is being sent.
```
#[reflectapi(flatten)]
pub some_property: SomeType
```

It could automatically add `#[serde(flatten)]`, or could require specifying both
```
#[reflectapi(flatten)]
#[serde(flatten)]
pub some_property: SomeType
```

**Comment by andyyu2004** [comment]
Hi @elilabes, can you provide a problematic example please? AFAICT reflectapi respects `[serde(flatten)]` in the generated code (rs and ts) and on the wire.

**Comment by elilabes** [comment]
Ah it seems that it does work - apologies. This stemmed from a slack thread before client was building.

It flattens like this: 
```
type SomeType = { ... } & SomeOtherType
```
