### ISSUE TITLE
Errors returned should implement `std::error::Error`

### ISSUE THREAD

**Issue by andyyu2004** [thepartly/reflectapi#34]
For example, the error type in `Result<(crate::Schema, Vec<Router<S>>), Vec<crate::ValidationError>>` does not implement `Error` which makes it requires manual handling.

**Comment by avkonst** [comment]
What is manual handling here? It is quite possible responses contain structures which do not have Error implemented...

**Comment by andyyu2004** [comment]
As in you can't easily propagate the error using `?` using `Box<dyn Error>` or `anyhow::Error` as the outer error type.

**Comment by avkonst** [comment]
And where do we need to do such propagation?

**Comment by andyyu2004** [comment]
It's rather minor but just in `main` or wherever where you just want to throw the error up.

```
    let (schema, routers) = match reflectapi::Builder::new()
        .name("lookup-server-cdc".into())
        .build()
    {
        Ok(ok) => ok,
        Err(errs) => {
            for err in errs {
                tracing::error!("{err}");
            }
            return Err(anyhow::anyhow!("build reflectapi schema"));
        }
    };
```

Why not be able to just do `.build()?` and then have the error implementation do the pretty printing.

**Comment by avkonst** [comment]
I see. It is only for build method. Sure it is fine to require it... not sure how you improve it.
