### ISSUE TITLE
PascalCase is not allied to enum variants in oepnapi doc codegen

### ISSUE THREAD

**Issue by avkonst** [thepartly/reflectapi#39]
![image](https://github.com/user-attachments/assets/7854fd59-bee6-48d7-a856-6e81aaa02e59)
Replace_all should be ReplaceAll

**Comment by avkonst** [comment]
or it should stay as replace_all as the underlying property...
If not possible, then this ticket can be rejected.

**Comment by andyyu2004** [comment]
This is a bit confusing. I think the snake_case conversion is working and he UI is just capitalizing the first letter making it look odd. 

What I don't understand is why `Replace_all` even has a subfield. That is probably a bug..

**Comment by andyyu2004** [comment]
I think we can close this, there's not much to be done about the doc renderer changing casings.. I think I've fixed the bug in #40
