### ISSUE TITLE
Better error types in generated rust clients

### ISSUE THREAD

**Issue by hardbyte** [thepartly/reflectapi#63]
Consider whether the generated errors should implement `std::error::Error`

**Comment by andyyu2004** [comment]
It does already if the generics do.

```rust
impl<AE: std::error::Error, NE: std::error::Error> std::error::Error for Error<AE, NE> {}
```

Did notice it was missing `source`though.  If you can review #64 .

**Comment by andyyu2004** [comment]
Is there anything else required here? Presumably the inner types were missing the impl? Can you close if all good please.
